// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFMp3y0P_00s4PM7w4nsEAn3ZZgEFLoII',
    appId: '1:561031004410:web:10ed06b278f459eed1c943',
    messagingSenderId: '561031004410',
    projectId: 'opslagstavlen-3dcce',
    authDomain: 'opslagstavlen-3dcce.firebaseapp.com',
    storageBucket: 'opslagstavlen-3dcce.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBA1fGl6M-d0WfkbDEbM-bssrZ3d2zM5J0',
    appId: '1:561031004410:android:2579ec0dd36df079d1c943',
    messagingSenderId: '561031004410',
    projectId: 'opslagstavlen-3dcce',
    storageBucket: 'opslagstavlen-3dcce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3eDhTLExKiQ-hC_esJOn_eqaTbjxmwtI',
    appId: '1:561031004410:ios:44cdd42a10e91534d1c943',
    messagingSenderId: '561031004410',
    projectId: 'opslagstavlen-3dcce',
    storageBucket: 'opslagstavlen-3dcce.appspot.com',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3eDhTLExKiQ-hC_esJOn_eqaTbjxmwtI',
    appId: '1:561031004410:ios:13f00531e677813cd1c943',
    messagingSenderId: '561031004410',
    projectId: 'opslagstavlen-3dcce',
    storageBucket: 'opslagstavlen-3dcce.appspot.com',
    iosBundleId: 'com.example.flutterApplication2.RunnerTests',
  );
}
